<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="wheel_separation" value="0.64" />
    <xacro:property name="wheel_radius" value="0.2" />
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">

            <!-- wheels -->
            <num_wheel_pairs>2</num_wheel_pairs>
            <left_joint>front_left_wheel_joint</left_joint>
            <right_joint>front_right_wheel_joint</right_joint>
            <left_joint>rear_left_wheel_joint</left_joint>
            <right_joint>rear_right_wheel_joint</right_joint>

            <!-- kinematics -->
            <wheel_separation> ${wheel_separation}</wheel_separation>
            <wheel_separation>${wheel_separation}</wheel_separation>
            <wheel_diameter>${wheel_radius * 2}</wheel_diameter>
            <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

            <!-- Update rate in Hz -->
            <updateRate>10</updateRate>
            <publishRate>30</publishRate>

            <!-- limits -->
            <max_wheel_torque>20</max_wheel_torque>
            <max_wheel_acceleration>5</max_wheel_acceleration>

            <!-- input -->
            <command_topic>cmd_vel</command_topic>

            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            <odometry_frame>odom</odometry_frame>
            <odometry_topic>odom</odometry_topic>
            <robot_base_frame>base_link</robot_base_frame>


        </plugin>


    </gazebo>
</robot>